app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin_area_common:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

admin_area_crud:
    resource: .
    type: sonata_admin
    prefix: /admin