homepage:
    path: /
    defaults:
        _controller: AppBundle:Default:index

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /forgot-password

fos_user_profile:
    prefix: /profile
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_change_password:
    prefix: /profile
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

fos_user_registration_register:
    path: /register
    defaults:
        _controller: FOSUserBundle:Registration:register

admin_area_common:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

admin_area_crud:
    resource: .
    type: sonata_admin
    prefix: /admin