---
server:
    install: '1'
    packages: [vim, git, nodejs, npm]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /var/www/quizzapp/web
    servername: quizzapp.dev
mysql:
    install: '1'
    root_password: root
    database: quizz_app
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-fpm, php5-mysql]
xdebug:
    install: '1'
composer:
    install: '1'

