services:
    app.event_subscriber.fos_user:
        class: AppBundle\EventSubscriber\FOSUserSubscriber
        arguments:
            - "@fos_user.user_manager"
        tags:
            - { name: kernel.event_subscriber }